# include <iostream>
using namespace std;
// generated by hunain riasat

int main(){


int a =21 ,b =400;
float pie = 3.14;
char c ='h';
bool hunain = "male";


 cout<<"This is the lecture 4.\nRemember that backslach n refers to a line breake.\nHere the value of a is "<<a<<".\nThe value of b is "<<b;
 cout<<"\nThe value of pie is "<<pie;
 cout<<"\nThe value of c is "<<c;
 cout<<"\nHUNAIN is MALE";
 
 
 return 0;
}